version: '3'
services:

  sai-auth:
    build:
      context: ./saiAuth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8800:8800"
      - "8803:8803"

  sai-storage:
    build:
      context: ./saiStorage
      dockerfile: Dockerfile
    ports:
      - "8801:8801"
      - "8802:8802"

  sai-contract-explorer:
    build:
      context: ./saiContractExplorer
      dockerfile: Dockerfile
    ports:
      - "8817:8817"
    volumes:
      - ./saiContractExplorer/build/block.data:/srv/block.data
      - ./saiContractExplorer/build/config.json:/srv/config.json

