version: '3'
services:

  sai-eth-manager:
    build:
      context: ./saiEthManager
      dockerfile: Dockerfile
    ports:
      - "8819:8080"

  sai-gn-monitor:
    build:
      context: ./saiGNMonitor
      dockerfile: Dockerfile
    ports:
      - "8820:8080"
