version: '3'
services:

  sai-auth:
    build:
      context: ./saiAuth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8800:8800"
      - "8803:8803"

  sai-storage:
    build:
      context: ./saiStorage
      dockerfile: Dockerfile
    ports:
      - "8801:8801"
      - "8802:8802"
#
#  sai-gn-monitor:
#    build:
#      context: ./saiGNMonitor
#      dockerfile: Dockerfile
#    ports:
#      - "8820:8080"
