version: '3'
services:

  sai-storage:
    build:
      context: ./saiStorage
      dockerfile: Dockerfile
    ports:
      - "8818:8818"

  sai-contract-explorer:
    build:
      context: ./saiContractExplorer
      dockerfile: Dockerfile
    ports:
      - "8817:8817"
    volumes:
      - ./saiContractExplorer/build/block.data:/srv/block.data
      - ./saiContractExplorer/build/config.json:/srv/config.json
